version: 2.1

jobs:
  commit_stage:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-rstreamer-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-rstreamer-{{ .Branch }}-
            - maven-repo-rstreamer-
      - run:
          name: Fetching dependencies
          command: ./mvnw dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-rstreamer-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Maven build & Sonar analysis
          command: ./mvnw verify -B sonar:sonar -Dsonar.projectKey=ikhoury_rstreamer -Dsonar.organization=ikhoury -Dsonar.host.url=https://sonarcloud.io
      - store_test_results:
          path: target/surefire-reports

  publish_artifact:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-rstreamer-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-rstreamer-{{ .Branch }}-
            - maven-repo-rstreamer-
      - run:
          name: Import GPG Key
          command: echo -e "$GPG_KEY" | gpg --import
      - run:
          name: Create and publish artifact
          command: ./mvnw -B -s .circleci/settings.xml -P release -DskipTests deploy

workflows:
  main:
    jobs:
      - commit_stage:
          context: SonarCloud
      - publish_artifact:
          context: Sonatype
          requires:
            - commit_stage
          filters:
            branches:
              only: master