version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install JDK 11
          command: sudo apt-get update && sudo apt-get install openjdk-11-jdk -y
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-rstreamer-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-rstreamer-{{ .Branch }}-
            - maven-repo-rstreamer-
      - run:
          name: Fetching dependencies
          command: JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ ./mvnw dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-rstreamer-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Maven build & Sonar analysis
          command: JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ ./mvnw verify -B sonar:sonar -Dsonar.projectKey=ikhoury_rstreamer -Dsonar.organization=ikhoury -Dsonar.host.url=https://sonarcloud.io
      - store_test_results:
          path: target/surefire-reports

  publish:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install JDK 11
          command: sudo apt-get update && sudo apt-get install openjdk-11-jdk -y
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-rstreamer-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-rstreamer-{{ .Branch }}-
            - maven-repo-rstreamer-
      - run:
          name: Fetching dependencies
          command: JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ ./mvnw dependency:go-offline
      - run:
          name: Import GPG Key
          command: echo -e "$GPG_KEY" | gpg --import
      - run:
          name: Create and publish artifact
          command: JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ ./mvnw -B -s .circleci/settings.xml -P release -DskipTests deploy

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - publish:
          context: Sonatype
          requires:
            - build
          filters:
            branches:
              only: master
