version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

jobs:
  commit_stage:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: mvn install -B
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - commit_stage:
          context: SonarCloud