version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
executorType: machine
jobs:
  build:
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Commit stage
          command: mvn install -B
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud