version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
jobs:
  executor: machine
  commit_stage:
    steps:
      - checkout
      - run: mvn install -B
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - commit_stage:
          context: SonarCloud