version: 2.1

jobs:
  commit_stage:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
    - run:
        name: Maven build and Sonar analysis
        command: mvn verify -B sonar:sonar -Dsonar.projectKey=ikhoury_rstreamer -Dsonar.organization=ikhoury -Dsonar.host.url=https://sonarcloud.io

workflows:
  main:
    jobs:
      - commit_stage:
          context: SonarCloud